package pointofsales;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import javax.swing.JOptionPane;
/**
 *
 * @author Anum
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form LoginGUI
     */
   
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lbllUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        jUsername = new javax.swing.JTextField();
        ResetBtn = new javax.swing.JButton();
        LoginBtn1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPassword = new javax.swing.JPasswordField();
        jCheckBoxShowPassword = new javax.swing.JCheckBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(java.awt.Color.white);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbllUsername.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        lbllUsername.setText("Username");
        jPanel1.add(lbllUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 170, -1, -1));

        lblPassword.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        lblPassword.setText("Password");
        jPanel1.add(lblPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        jUsername.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jPanel1.add(jUsername, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 130, -1));

        ResetBtn.setBackground(javax.swing.UIManager.getDefaults().getColor("InternalFrame.inactiveTitleGradient"));
        ResetBtn.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        ResetBtn.setText("Reset");
        ResetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetBtnActionPerformed(evt);
            }
        });
        jPanel1.add(ResetBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, -1, -1));

        LoginBtn1.setBackground(javax.swing.UIManager.getDefaults().getColor("InternalFrame.inactiveTitleGradient"));
        LoginBtn1.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        LoginBtn1.setText("Login");
        LoginBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBtn1ActionPerformed(evt);
            }
        });
        jPanel1.add(LoginBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 260, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pointOfSales/userIcon.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 190, 110));
        jPanel1.add(jPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 130, -1));

        jCheckBoxShowPassword.setBackground(java.awt.Color.white);
        jCheckBoxShowPassword.setText("Show Password");
        jCheckBoxShowPassword.setToolTipText("");
        jCheckBoxShowPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBoxShowPasswordMouseClicked(evt);
            }
        });
        jPanel1.add(jCheckBoxShowPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 230, 130, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 352, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ResetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetBtnActionPerformed
        // TODO add your handling code here:
        jUsername.setText(null);
        jPassword.setText(null);
    }//GEN-LAST:event_ResetBtnActionPerformed

    private void LoginBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBtn1ActionPerformed
   
        String username = jUsername.getText();
        String password = jPassword.getText();
        
        if(password.contains("sup") && username.contains("Anum")){
             this.dispose();
            POS frame = new POS();
            frame.setVisible(true);
    
        }
        else
            JOptionPane.showMessageDialog(null, "Invalid Username/Password", "Login Error", JOptionPane.ERROR_MESSAGE); 
            jUsername.setText(null);
            jPassword.setText(null);
    }//GEN-LAST:event_LoginBtn1ActionPerformed

    private void jCheckBoxShowPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxShowPasswordMouseClicked
        // TODO add your handling code here:
         if(jCheckBoxShowPassword.isSelected())
        {
           jPassword.setEchoChar((char)0);
        }
        else
        {
           jPassword.setEchoChar('*');
        }
    }//GEN-LAST:event_jCheckBoxShowPasswordMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LoginBtn1;
    private javax.swing.JButton ResetBtn;
    private javax.swing.JCheckBox jCheckBoxShowPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPassword;
    private javax.swing.JTextField jUsername;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lbllUsername;
    // End of variables declaration//GEN-END:variables
}
