package pointofsales;


import pointofsales.Database;
//import com.mysql.jdbc.Statement;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author Anum Khalid
 */
public class POS extends javax.swing.JFrame {
    
   Discount dObj;

   int purchase [] = new int[3];
   int Quantity [] = new int [9];
   int drink []= new int[1];
    
   int iEspresso = 335;
   int iCuppucino = 545;
   int iIcedEspresso = 600;
   int iCaramel = 600;
   int iAmericano = 600;
   int iJava = 600;
   int iStrawberry = 600;
   int iVanilla = 600;
   int iChocolate = 600;
    /**
     * Creates new form POS
     */
    public POS() {
        initComponents();
         dObj = new Discount(this);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textInvoice = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jEspresso = new javax.swing.JTextField();
        jCappuccino = new javax.swing.JTextField();
        jIcedEspresso = new javax.swing.JTextField();
        jCaramel = new javax.swing.JTextField();
        jIcedAmericano = new javax.swing.JTextField();
        jVanilla = new javax.swing.JTextField();
        jJava = new javax.swing.JTextField();
        jStrawberry = new javax.swing.JTextField();
        jCheckBoxChocolate = new javax.swing.JCheckBox();
        jCheckBoxEspresso = new javax.swing.JCheckBox();
        jCheckBoxCappuccino = new javax.swing.JCheckBox();
        jCheckBoxIced = new javax.swing.JCheckBox();
        jCheckBoxCaramel = new javax.swing.JCheckBox();
        jCheckBoxAmericano = new javax.swing.JCheckBox();
        jCheckBoxVanilla = new javax.swing.JCheckBox();
        jCheckBoxJava = new javax.swing.JCheckBox();
        jCheckBoxStrawberry = new javax.swing.JCheckBox();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jChocolate = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        btnTotal = new javax.swing.JButton();
        btnInvoice = new javax.swing.JButton();
        jbtnSave = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnDiscount = new javax.swing.JButton();
        btnAddDiscount = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        lblTax1 = new javax.swing.JLabel();
        lblSubTotal1 = new javax.swing.JLabel();
        lblTotal1 = new javax.swing.JLabel();
        jSubTotal = new javax.swing.JTextField();
        jTax = new javax.swing.JTextField();
        jTotal = new javax.swing.JTextField();
        jDiscount = new javax.swing.JTextField();
        jDiscountTotal = new javax.swing.JTextField();
        lblTotal2 = new javax.swing.JLabel();
        lblTotal7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        btnExit = new javax.swing.JButton();
        jbtnRecord = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.Color.white);
        setMinimumSize(new java.awt.Dimension(900, 460));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(java.awt.Color.white);
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        textInvoice.setColumns(20);
        textInvoice.setRows(5);
        jScrollPane1.setViewportView(textInvoice);

        jPanel4.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 120, 280, 420));
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 60));

        jPanel1.setBackground(java.awt.SystemColor.controlLtHighlight);
        jPanel1.setForeground(new java.awt.Color(51, 51, 51));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jEspresso.setText("0");
        jPanel1.add(jEspresso, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 30, 60, -1));

        jCappuccino.setText("0");
        jPanel1.add(jCappuccino, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 70, 60, -1));

        jIcedEspresso.setText("0");
        jPanel1.add(jIcedEspresso, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 110, 60, -1));

        jCaramel.setText("0");
        jPanel1.add(jCaramel, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 60, -1));

        jIcedAmericano.setText("0");
        jPanel1.add(jIcedAmericano, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 190, 60, -1));

        jVanilla.setText("0");
        jPanel1.add(jVanilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 60, -1));

        jJava.setText("0");
        jPanel1.add(jJava, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 60, -1));

        jStrawberry.setText("0");
        jPanel1.add(jStrawberry, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 310, 60, -1));

        jCheckBoxChocolate.setBackground(new java.awt.Color(204, 153, 255));
        jCheckBoxChocolate.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jCheckBoxChocolate.setText("Chocolate Chip Frappuccino");
        jCheckBoxChocolate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBoxChocolateMouseClicked(evt);
            }
        });
        jPanel1.add(jCheckBoxChocolate, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 350, 200, -1));

        jCheckBoxEspresso.setBackground(new java.awt.Color(204, 153, 255));
        jCheckBoxEspresso.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jCheckBoxEspresso.setText("Espresso");
        jCheckBoxEspresso.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBoxEspressoMouseClicked(evt);
            }
        });
        jPanel1.add(jCheckBoxEspresso, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 33, 200, 20));

        jCheckBoxCappuccino.setBackground(new java.awt.Color(204, 153, 255));
        jCheckBoxCappuccino.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jCheckBoxCappuccino.setText("Cappuccino");
        jCheckBoxCappuccino.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBoxCappuccinoMouseClicked(evt);
            }
        });
        jPanel1.add(jCheckBoxCappuccino, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 200, -1));

        jCheckBoxIced.setBackground(new java.awt.Color(204, 153, 255));
        jCheckBoxIced.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jCheckBoxIced.setText("Iced Espresso");
        jCheckBoxIced.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBoxIcedMouseClicked(evt);
            }
        });
        jPanel1.add(jCheckBoxIced, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 200, -1));

        jCheckBoxCaramel.setBackground(new java.awt.Color(204, 153, 255));
        jCheckBoxCaramel.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jCheckBoxCaramel.setText("Caramel Macchiato");
        jCheckBoxCaramel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBoxCaramelMouseClicked(evt);
            }
        });
        jPanel1.add(jCheckBoxCaramel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 150, 200, -1));

        jCheckBoxAmericano.setBackground(new java.awt.Color(204, 153, 255));
        jCheckBoxAmericano.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jCheckBoxAmericano.setText("Iced Caffe Americano");
        jCheckBoxAmericano.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBoxAmericanoMouseClicked(evt);
            }
        });
        jPanel1.add(jCheckBoxAmericano, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 200, -1));

        jCheckBoxVanilla.setBackground(new java.awt.Color(204, 153, 255));
        jCheckBoxVanilla.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jCheckBoxVanilla.setText("Vanilla Frappuccino");
        jCheckBoxVanilla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBoxVanillaMouseClicked(evt);
            }
        });
        jPanel1.add(jCheckBoxVanilla, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 230, 200, -1));

        jCheckBoxJava.setBackground(new java.awt.Color(204, 153, 255));
        jCheckBoxJava.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jCheckBoxJava.setText("Java Chip Frappuccino");
        jCheckBoxJava.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBoxJavaMouseClicked(evt);
            }
        });
        jPanel1.add(jCheckBoxJava, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, 200, -1));

        jCheckBoxStrawberry.setBackground(new java.awt.Color(204, 153, 255));
        jCheckBoxStrawberry.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jCheckBoxStrawberry.setText("Strawberry Frappuccino");
        jCheckBoxStrawberry.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBoxStrawberryMouseClicked(evt);
            }
        });
        jPanel1.add(jCheckBoxStrawberry, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 310, 200, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Items");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 60, -1));

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Quantity");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 10, 60, -1));

        jChocolate.setText("0");
        jPanel1.add(jChocolate, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 60, -1));

        jPanel4.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 100, 320, 390));

        jPanel2.setBackground(java.awt.SystemColor.controlLtHighlight);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnTotal.setBackground(javax.swing.UIManager.getDefaults().getColor("InternalFrame.inactiveTitleGradient"));
        btnTotal.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        btnTotal.setText("Total");
        btnTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalActionPerformed(evt);
            }
        });
        jPanel2.add(btnTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 90, 30));

        btnInvoice.setBackground(javax.swing.UIManager.getDefaults().getColor("InternalFrame.activeTitleGradient"));
        btnInvoice.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        btnInvoice.setText("Invoice");
        btnInvoice.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInvoiceActionPerformed(evt);
            }
        });
        jPanel2.add(btnInvoice, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 90, 30));

        jbtnSave.setBackground(javax.swing.UIManager.getDefaults().getColor("InternalFrame.activeTitleGradient"));
        jbtnSave.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jbtnSave.setText("Save");
        jbtnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnSaveActionPerformed(evt);
            }
        });
        jPanel2.add(jbtnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 90, 30));

        btnReset.setBackground(javax.swing.UIManager.getDefaults().getColor("InternalFrame.activeTitleGradient"));
        btnReset.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        jPanel2.add(btnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 90, 30));

        btnDiscount.setBackground(javax.swing.UIManager.getDefaults().getColor("InternalFrame.activeTitleGradient"));
        btnDiscount.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        btnDiscount.setText("Discount");
        btnDiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDiscountActionPerformed(evt);
            }
        });
        jPanel2.add(btnDiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 90, 30));

        btnAddDiscount.setBackground(javax.swing.UIManager.getDefaults().getColor("InternalFrame.activeTitleGradient"));
        btnAddDiscount.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        btnAddDiscount.setText("Add Dis%");
        btnAddDiscount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddDiscountActionPerformed(evt);
            }
        });
        jPanel2.add(btnAddDiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 120, 90, 30));

        jPanel4.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 360, 230, 180));

        jPanel3.setBackground(java.awt.SystemColor.controlLtHighlight);
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTax1.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        lblTax1.setText("Tax");
        jPanel3.add(lblTax1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 40, 30));

        lblSubTotal1.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        lblSubTotal1.setText("SubTotal");
        jPanel3.add(lblSubTotal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 50, 20));

        lblTotal1.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        lblTotal1.setText("After Discount");
        jPanel3.add(lblTotal1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, -1, 20));
        jPanel3.add(jSubTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 70, -1));

        jTax.setText("128");
        jPanel3.add(jTax, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 70, -1));
        jPanel3.add(jTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 100, 70, -1));
        jPanel3.add(jDiscount, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 70, -1));
        jPanel3.add(jDiscountTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 180, 70, -1));

        lblTotal2.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        lblTotal2.setText("Discount");
        jPanel3.add(lblTotal2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, -1, 20));

        lblTotal7.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        lblTotal7.setText("Total");
        jPanel3.add(lblTotal7, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, -1, 20));

        jPanel4.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 120, 210, 230));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pointOfSales/Banner.jpg"))); // NOI18N
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 80));

        jPanel5.setBackground(java.awt.SystemColor.controlLtHighlight);
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnExit.setBackground(javax.swing.UIManager.getDefaults().getColor("InternalFrame.activeTitleGradient"));
        btnExit.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        jPanel5.add(btnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 90, 30));

        jbtnRecord.setBackground(javax.swing.UIManager.getDefaults().getColor("InternalFrame.activeTitleGradient"));
        jbtnRecord.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jbtnRecord.setText("Records");
        jbtnRecord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnRecordActionPerformed(evt);
            }
        });
        jPanel5.add(jbtnRecord, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 90, 30));

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 490, 280, 60));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 570));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTotalActionPerformed
        // TODO add your handling code here:

        Quantity[0] = Integer.parseInt(jEspresso.getText()) * iEspresso; 
	Quantity[1] = Integer.parseInt(jCappuccino.getText()) * iCuppucino;
	Quantity[2] = Integer.parseInt(jIcedEspresso.getText()) * iIcedEspresso;
	Quantity[3] = Integer.parseInt(jCaramel.getText()) * iCaramel;
	Quantity[4] = Integer.parseInt(jIcedAmericano.getText())* iAmericano;
	Quantity[5] = Integer.parseInt(jVanilla.getText())* iJava;
        Quantity[6] = Integer.parseInt(jJava.getText())* iStrawberry;
	Quantity[7] = Integer.parseInt(jStrawberry.getText())* iVanilla;
	Quantity[8] = Integer.parseInt(jChocolate.getText())* iChocolate;
    //    Quantity[9] = Integer.parseInt(jQItem.getText())* jItemPrice;
        
        purchase[0] = Quantity[0] + Quantity[1]+ Quantity[2]+ Quantity[3] + Quantity[4];
        purchase[1] =  Quantity[5] + Quantity[6]+ Quantity[7]+ Quantity[8];
        purchase[2] = purchase[0] + purchase[1];
      
       int Subtotal =  purchase[2];
        
        String isubtotal = String.format("%d", Subtotal);
        jSubTotal.setText(isubtotal);
        
        int tax =  Integer.parseInt(jTax.getText());
        
        int allTotal = purchase[2] + tax;
        
        String Total = String.format("%d", allTotal );
        jTotal.setText(Total);
        
        
    }//GEN-LAST:event_btnTotalActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
       
        jEspresso.setText("0");
        jCappuccino.setText("0");
        jIcedEspresso.setText("0");
        jCaramel.setText("0");
        jIcedAmericano.setText("0");
        jVanilla.setText("0");
        jJava.setText("0");
        jStrawberry.setText("0");
        textInvoice.setEnabled(true);
        textInvoice.setText(null);
        jSubTotal.setText("0");
        jTotal.setText(null);
        jDiscount.setText(null);
        jDiscountTotal.setText(null);
        jCheckBoxEspresso.setSelected(false);
        jCheckBoxChocolate.setSelected(false);
        jCheckBoxCappuccino.setSelected(false);
        jCheckBoxIced.setSelected(false);
        jCheckBoxCaramel.setSelected(false);
        jCheckBoxAmericano.setSelected(false);
        jCheckBoxVanilla.setSelected(false);
        jCheckBoxJava.setSelected(false);
        jCheckBoxStrawberry.setSelected(false);
   
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        // TODO add your handling code here:
        JFrame frame = new JFrame();
        if(JOptionPane.showConfirmDialog(frame, "Are you sure?", "Coffee Beans", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION) {
             System.exit(0);
        }
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnInvoiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInvoiceActionPerformed
  
        textInvoice.setEnabled(true);
	int ref = 1345 + (int) (Math.random()*155);
        
        Calendar timer = Calendar.getInstance();
	timer.getTime();
	SimpleDateFormat Time1 = new SimpleDateFormat("HH:mm:ss");
	Time1.format(timer.getTime());
	SimpleDateFormat Tdate = new SimpleDateFormat("dd-MM-yyyy");
	Tdate.format(timer.getTime());
     
        textInvoice.append("======================================\n" +
                           "COFFEE BEANS\n" +
                           "======================================\n" +
                 
                           "Reference: " + ref + "\n\n" +
                                   
                 	   "Date: " +Tdate.format(timer.getTime()) + "\n" +"Time: "+Time1.format(timer.getTime()) + "\n" +
                           
                           "\n Espresso:\t\t" +jEspresso.getText() +
                           "\n Cappuccino:\t\t" +jCappuccino.getText() +
                           "\n Iced Espresso:\t\t" +jIcedEspresso.getText() + 
                           "\n Caramel Macchiato:\t" +jCaramel.getText() +	 
                           "\n Iced Caffè Americano:\t" +jIcedAmericano.getText() + 
                           "\n Caffè Vanilla Frappuccino:\t" +jVanilla.getText() + 
                           "\n Java Chip Frappuccino:\t" +jJava.getText() + 
	                   "\n Strawberry Frappuccino:\t" +jStrawberry.getText() +
	                   "\n Chocolate Chip Frappuccino:\t" +jChocolate.getText() +
                           "\n -----------------------------------------------------------\n" +
	                   " Tax:\t\t" +jTax.getText() +
	                   "\n SubTotal:\t\t" +jSubTotal.getText() +
                           "\n Discount:\t\t" +jDiscount.getText() +
                           "\n Total:\t\t" +jTotal.getText() +
                           "\n Payment with Discount:\t\t" +jDiscountTotal.getText() +
                
                           "\n ------------------------------------------------------------\n" +

	                   "\n Keep visiting Coffee Beans.");
  
        
    }//GEN-LAST:event_btnInvoiceActionPerformed

    private void jCheckBoxEspressoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxEspressoMouseClicked
        // TODO add your handling code here:
        if(jCheckBoxEspresso.isSelected()){
            jEspresso.setEnabled(true);
            jEspresso.setText("");
            jEspresso.requestFocus();
        }
        else
        {
            jEspresso.setEnabled(false);
            jEspresso.setText("0");
        }
    }//GEN-LAST:event_jCheckBoxEspressoMouseClicked

    private void jCheckBoxCappuccinoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxCappuccinoMouseClicked
        // TODO add your handling code here:
        if(jCheckBoxCappuccino.isSelected()){
            jCappuccino.setEnabled(true);
            jCappuccino.setText("");
            jCappuccino.requestFocus();
        }
        else
        {
            jCappuccino.setEnabled(false);
            jCappuccino.setText("0");
        }
    }//GEN-LAST:event_jCheckBoxCappuccinoMouseClicked

    private void jCheckBoxIcedMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxIcedMouseClicked
        // TODO add your handling code here:
        if(jCheckBoxIced.isSelected()){
           jIcedEspresso.setEnabled(true);
            jIcedEspresso.setText("");
            jIcedEspresso.requestFocus();
        }
        else
        {
           jIcedEspresso.setEnabled(false);
           jIcedEspresso.setText("0");
        }
    }//GEN-LAST:event_jCheckBoxIcedMouseClicked

    private void jCheckBoxCaramelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxCaramelMouseClicked
        // TODO add your handling code here:
        if(jCheckBoxCaramel.isSelected()){
            jCaramel.setEnabled(true);
            jCaramel.setText("");
            jCaramel.requestFocus();
        }
        else
        {
            jCaramel.setEnabled(false);
            jCaramel.setText("0");
        }
    }//GEN-LAST:event_jCheckBoxCaramelMouseClicked

    private void jCheckBoxAmericanoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxAmericanoMouseClicked
        // TODO add your handling code here:
        if(jCheckBoxAmericano.isSelected()){
            jIcedAmericano.setEnabled(true);
            jIcedAmericano.setText("");
            jIcedAmericano.requestFocus();
        }
        else
        {
            jIcedAmericano.setEnabled(false);
            jIcedAmericano.setText("0");
        }
    }//GEN-LAST:event_jCheckBoxAmericanoMouseClicked

    private void jCheckBoxVanillaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxVanillaMouseClicked
        // TODO add your handling code here:
        if(jCheckBoxVanilla.isSelected()){
            jVanilla.setEnabled(true);
            jVanilla.setText("");
            jVanilla.requestFocus();
        }
        else
        {
            jVanilla.setEnabled(false);
            jVanilla.setText("0");
        }
    }//GEN-LAST:event_jCheckBoxVanillaMouseClicked

    private void jCheckBoxJavaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxJavaMouseClicked
        // TODO add your handling code here:
        if(jCheckBoxJava.isSelected()){
            jJava.setEnabled(true);
            jJava.setText("");
            jJava.requestFocus();
        }
        else
        {
            jJava.setEnabled(false);
            jJava.setText("0");
        }
    }//GEN-LAST:event_jCheckBoxJavaMouseClicked

    private void jCheckBoxStrawberryMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxStrawberryMouseClicked
        // TODO add your handling code here:
        if(jCheckBoxStrawberry.isSelected()){
            jStrawberry.setEnabled(true);
            jStrawberry.setText("");
            jStrawberry.requestFocus();
        }
        else
        {
            jStrawberry.setEnabled(false);
            jStrawberry.setText("0");
        }
    }//GEN-LAST:event_jCheckBoxStrawberryMouseClicked

    private void jCheckBoxChocolateMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBoxChocolateMouseClicked
        // TODO add your handling code here:
        if(jCheckBoxChocolate.isSelected()){
            jChocolate.setEnabled(true);
            jChocolate.setText("");
            jChocolate.requestFocus();
        }
        else
        {
            jChocolate.setEnabled(false);
            jChocolate.setText("0");
        }
    }//GEN-LAST:event_jCheckBoxChocolateMouseClicked

    private void jbtnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnSaveActionPerformed
        // TODO add your handling code here:
        try{
            Connection cn = Database.getConnection();
            String sql = "Insert into dailyamount(TotalCashReceived) values(?)";
            PreparedStatement ps = cn.prepareStatement(sql);
            ps.setString(1, jTotal.getText());
            ps.execute();
            JOptionPane.showMessageDialog(this, "saved");
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
        } 
    }//GEN-LAST:event_jbtnSaveActionPerformed

    private void jbtnRecordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnRecordActionPerformed
        // TODO add your handling code here:
        Security frame = new Security();
        frame.setVisible(true);
    }//GEN-LAST:event_jbtnRecordActionPerformed

    private void btnDiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDiscountActionPerformed
        // TODO add your handling code here:
 
        try{
            int DiscountAdded = Integer.parseInt(jDiscount.getText());
            int TotalReceived = Integer.parseInt(jTotal.getText()); 
            int subtraction = TotalReceived - DiscountAdded;  
            String DisTotal = String.format("%d", subtraction );
            jDiscountTotal.setText(DisTotal);
         }
         catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error: Select DISCOUNT button first");
        }
    }//GEN-LAST:event_btnDiscountActionPerformed

    private void btnAddDiscountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddDiscountActionPerformed
        // TODO add your handling code here:
      try{
            dObj.discount();
            updateScreen();
         }
         catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error: Select DISCOUNT button first");
        }
    }//GEN-LAST:event_btnAddDiscountActionPerformed
    
    private void updateScreen(){
        String value = Integer.toString(dObj.discounts);
        jDiscount.setText(value);
        
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(POS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(POS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(POS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(POS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new POS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddDiscount;
    private javax.swing.JButton btnDiscount;
    private javax.swing.JButton btnExit;
    private javax.swing.JButton btnInvoice;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTotal;
    private javax.swing.JTextField jCappuccino;
    private javax.swing.JTextField jCaramel;
    private javax.swing.JCheckBox jCheckBoxAmericano;
    private javax.swing.JCheckBox jCheckBoxCappuccino;
    private javax.swing.JCheckBox jCheckBoxCaramel;
    private javax.swing.JCheckBox jCheckBoxChocolate;
    private javax.swing.JCheckBox jCheckBoxEspresso;
    private javax.swing.JCheckBox jCheckBoxIced;
    private javax.swing.JCheckBox jCheckBoxJava;
    private javax.swing.JCheckBox jCheckBoxStrawberry;
    private javax.swing.JCheckBox jCheckBoxVanilla;
    private javax.swing.JTextField jChocolate;
    private javax.swing.JTextField jDiscount;
    private javax.swing.JTextField jDiscountTotal;
    private javax.swing.JTextField jEspresso;
    private javax.swing.JTextField jIcedAmericano;
    private javax.swing.JTextField jIcedEspresso;
    private javax.swing.JTextField jJava;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jStrawberry;
    private javax.swing.JTextField jSubTotal;
    private javax.swing.JTextField jTax;
    public javax.swing.JTextField jTotal;
    private javax.swing.JTextField jVanilla;
    private javax.swing.JButton jbtnRecord;
    private javax.swing.JButton jbtnSave;
    private javax.swing.JLabel lblSubTotal1;
    private javax.swing.JLabel lblTax1;
    private javax.swing.JLabel lblTotal1;
    private javax.swing.JLabel lblTotal2;
    private javax.swing.JLabel lblTotal7;
    private javax.swing.JTextArea textInvoice;
    // End of variables declaration//GEN-END:variables
}
