/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pointofsales;

import pointofsales.POS;
import pointofsales.Database;
import com.mysql.jdbc.Statement;
import java.sql.Connection;
import java.sql.ResultSet;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Anum
 */
public class Records extends javax.swing.JFrame {

    /**
     * Creates new form Records
     */
    public Records() {
        initComponents();
         
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButtonView = new javax.swing.JButton();
        jRecordsCancel = new javax.swing.JButton();
        jRecordsReset = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableHistory = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(java.awt.SystemColor.controlLtHighlight);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(java.awt.SystemColor.controlLtHighlight);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonView.setBackground(javax.swing.UIManager.getDefaults().getColor("InternalFrame.inactiveTitleGradient"));
        jButtonView.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jButtonView.setText("View");
        jButtonView.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonViewActionPerformed(evt);
            }
        });
        jPanel1.add(jButtonView, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 30, 110, 30));

        jRecordsCancel.setBackground(javax.swing.UIManager.getDefaults().getColor("InternalFrame.inactiveTitleGradient"));
        jRecordsCancel.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jRecordsCancel.setText("Cancel");
        jRecordsCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRecordsCancelActionPerformed(evt);
            }
        });
        jPanel1.add(jRecordsCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 30, 100, 30));

        jRecordsReset.setBackground(javax.swing.UIManager.getDefaults().getColor("InternalFrame.inactiveTitleGradient"));
        jRecordsReset.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jRecordsReset.setText("Reset");
        jRecordsReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRecordsResetActionPerformed(evt);
            }
        });
        jPanel1.add(jRecordsReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 30, 100, 30));

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 10)); // NOI18N
        jLabel1.setForeground(javax.swing.UIManager.getDefaults().getColor("Desktop.background"));
        jLabel1.setText("powered by softwareBeans");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 60, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 460, 1080, 80));

        jPanel2.setBackground(java.awt.SystemColor.controlLtHighlight);
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TableHistory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "Record of Sales"
            }
        ));
        jScrollPane2.setViewportView(TableHistory);

        jPanel2.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 1040, 430));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1080, 470));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonViewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonViewActionPerformed
        // TODO add your handling code here:
        DefaultTableModel t =(DefaultTableModel)TableHistory.getModel();
        try{
            Connection cn = Database.getConnection();
            Statement st = (Statement) cn.createStatement();
            String q = "Select * from dailyamount";
            ResultSet s = st.executeQuery(q);

            while(s.next()){
                String data = s.getString("TotalCashReceived");
                t.addRow(new Object[]{data});       
            }
     
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, e);
            
        }
    }//GEN-LAST:event_jButtonViewActionPerformed

    private void jRecordsCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRecordsCancelActionPerformed
        // TODO add your handling code here:
         dispose();
         POS posObj = new POS();
         posObj.setVisible(true);
    }//GEN-LAST:event_jRecordsCancelActionPerformed

    private void jRecordsResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRecordsResetActionPerformed
        // TODO add your handling code here:
        DefaultTableModel t =(DefaultTableModel)TableHistory.getModel();
        t.setRowCount(0);

    }//GEN-LAST:event_jRecordsResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Records.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Records.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Records.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Records.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Records().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TableHistory;
    private javax.swing.JButton jButtonView;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jRecordsCancel;
    private javax.swing.JButton jRecordsReset;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
