/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package pointofsales;

import pointofsales.Records;
import pointofsales.POS;
import javax.swing.JOptionPane;

/**
 *
 * @author Anum
 */
public class Security extends javax.swing.JFrame {

    /**
     * Creates new form Security
     */
    public Security() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSecurityusername = new javax.swing.JTextField();
        jSecurityReset = new javax.swing.JButton();
        jSecurityCancel = new javax.swing.JButton();
        jSecurityAccess = new javax.swing.JButton();
        jSecurityPassword = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(java.awt.SystemColor.controlLtHighlight);
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/pointOfSales/128x128.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 140, 130));

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel2.setText("username");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jLabel3.setText("password");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));
        jPanel1.add(jSecurityusername, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 160, 140, -1));

        jSecurityReset.setBackground(javax.swing.UIManager.getDefaults().getColor("InternalFrame.inactiveTitleGradient"));
        jSecurityReset.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jSecurityReset.setText("Reset");
        jSecurityReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSecurityResetActionPerformed(evt);
            }
        });
        jPanel1.add(jSecurityReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 230, 70, 30));

        jSecurityCancel.setBackground(javax.swing.UIManager.getDefaults().getColor("InternalFrame.inactiveTitleGradient"));
        jSecurityCancel.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jSecurityCancel.setText("Cancel");
        jSecurityCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSecurityCancelActionPerformed(evt);
            }
        });
        jPanel1.add(jSecurityCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 80, 30));

        jSecurityAccess.setBackground(javax.swing.UIManager.getDefaults().getColor("InternalFrame.inactiveTitleGradient"));
        jSecurityAccess.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        jSecurityAccess.setText("Access");
        jSecurityAccess.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSecurityAccessActionPerformed(evt);
            }
        });
        jPanel1.add(jSecurityAccess, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 230, 70, 30));
        jPanel1.add(jSecurityPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 190, 140, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 290));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jSecurityResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSecurityResetActionPerformed
        // TODO add your handling code here:
        jSecurityusername.setText(null);
        jSecurityPassword.setText(null);
    }//GEN-LAST:event_jSecurityResetActionPerformed

    private void jSecurityCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSecurityCancelActionPerformed
        // TODO add your handling code here:
        dispose();
        POS posObj = new POS();
        posObj.setVisible(true);
        
    }//GEN-LAST:event_jSecurityCancelActionPerformed

    private void jSecurityAccessActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSecurityAccessActionPerformed
        // TODO add your handling code here:
        String Securityusername =  jSecurityusername.getText();
        String Securitypassword = jSecurityPassword.getText();
        
        if(Securitypassword.contains("sup") && Securityusername.contains("Anum")){
            this.dispose();
            Records frame = new Records();
            frame.setVisible(true);
    
        }
        else
            JOptionPane.showMessageDialog(null, "Access Denied", "Failed", JOptionPane.ERROR_MESSAGE); 
             jSecurityusername.setText(null);
            jSecurityPassword.setText(null);
    }//GEN-LAST:event_jSecurityAccessActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Security.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Security.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Security.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Security.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Security().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jSecurityAccess;
    private javax.swing.JButton jSecurityCancel;
    private javax.swing.JPasswordField jSecurityPassword;
    private javax.swing.JButton jSecurityReset;
    private javax.swing.JTextField jSecurityusername;
    // End of variables declaration//GEN-END:variables
}
